/gazebo_ros_control:
    pid_gains:
      front_right_wheel:
          p: 1000.0
          i: 20.0
          d: 0.0
      front_left_wheel:
          p: 1000.0
          i: 20.0
          d: 0.0
      rear_left_wheel:
          p: 1000.0
          i: 20.0
          d: 0.0
      rear_right_wheel:
          p: 1000.0
          i: 20.0
          d: 0.0
